### ISSUE TITLE
Rows and Columns Confusion

### ISSUE THREAD

**Issue by dngreenst** [sakopzon/GameOfLife#1]
I believe we have a confusion with rows and columns. 

Purely on naming level, I believe that the List that is underlying the Rows class should be a called row or something like that, definitely not columns - that's extremely confusing.

Secondly, we define what is a row and what is a column one way in our Board constructors, and another way in Row class. I believe that the definition in Row class is the correct one, and the ones in the constructors should be changed accordingly (I'd do it now, but I have to go to work tomorrow...).

**Comment by sakopzon** [comment]
The matrix is built as ArrayList of Rows (called rows), when Row is an ArrayList of Cells (called columns).

**Comment by sakopzon** [comment]
fixed it on revive so the provided tests passing
